### PR TITLE
BaSP-MR-97: Loading component created

### PR DESCRIPTION
**Pull request by YhanahiRosenthal**
Loading component created

### CODE REVIEW

**Review by FrancoLelli — APPROVED** [review]
Good Job! But if you use a Gif? I think its more easy

**Review by FrancoLelli — CHANGES_REQUESTED** [review]
Add description

**Review by Ginoboca1 — APPROVED** [review]
Looks great!

**Review by FrancoLelli — APPROVED** [review]
Good Job mate!!

**Pull request merged**
