### PR TITLE
BaSP-MR-340: fix-profile

### PR DESCRIPTION
**Pull request by Ginoboca1**
- Members, trainers and admins cannot edit his Email account.
- Changes Form profile buttons order

### CODE REVIEW

**Review by YhanahiRosenthal — APPROVED** [review]
Excellent job!

**Review by CristianLotorto — APPROVED** [review]
Nice!

**Review by CristianLotorto — APPROVED** [review]
Nice!

**Review by YhanahiRosenthal — APPROVED** [review]
Good job!

**Pull request merged**
