### PR TITLE
BaSP-MR-269: Navbar features left

### PR DESCRIPTION
**Pull request by maurojjzz**
i added Subscription and Activities features on admin perspective

### CODE REVIEW

**Review by Ginoboca1 — APPROVED** [review]
Nice Job!

**Comment by maurojjzz** [comment]
[[FIX] Admin Sidebar](https://trello.com/c/ykntWULm/269-fix-admin-sidebar)

**Review by YhanahiRosenthal — APPROVED** [review]
Good job!

**Review by CristianLotorto — APPROVED** [review]
Nice job!

**Pull request merged**
