### PR TITLE
BaSP-MR-344: Menu button shape

### PR DESCRIPTION
**Pull request by IvanJukonis**
This PR is related to ticket MR-344, which required that the styles of the auth buttons should not be modified when accessing an unauthorized route.

IMPORTANT. After discussing with the team, it has been decided that in the case of accessing an undesired route, the user should remain unauthorized and be redirected to the "not allowed" route without switching their role.

To achieve this, when accessing an unauthorized route, the user will be redirected to the "not allowed" route specific to the role they logged in with.

### CODE REVIEW

**Review by FrancoLelli — APPROVED** [review]
Nice!

**Review by YhanahiRosenthal — APPROVED** [review]
Amazing job man!

**Review by CristianLotorto — APPROVED** [review]
Nice work Ivo!

**Comment by maurojjzz** [comment]
[[BUG] GENERAL - The menu buttons change shape](https://trello.com/c/7GjVGcxK/344-bug-general-the-menu-buttons-change-shape)

**Pull request merged**
